### ISSUE TITLE
Please Put Clear Instructions On how to use

### ISSUE THREAD

**Issue by kush-singh-chb** [jifalops/simple_autocomplete_formfield#2]
I have been wanting to use your library and cant figure out how to pass it the list of Strings 
Can you please Help me out with it
thanks in advance

**Comment by jifalops** [comment]
Since each item may have a complex UI, you create the items using the [`itemBuilder`](https://github.com/jifalops/simple_autocomplete_formfield/blob/master/lib/simple_autocomplete_formfield.dart#L46) callback.

Say you have a class such as 

```dart
class Person {
  String name;
  String address;
}
```

Then to show a list of people you would use 

```dart
// In widget building function...
// Assume `people` is a `List<Person>`.
SimpleAutocompleteFormField<Person>(
  itemBuilder: (context, person) => 
      Column(children: [ Text(person.name), Text(person.address) ]),
  onSearch: (search) async => people.where((person) => 
      person.name.contains(search) || person.address.contains(search)),
)
```

The `itemParser` field is not always necessary but is how the text field is filled in when an item is tapped on. If omitted, it just uses the object's `toString()` method. `itemParser.fromString()` is how you would decide which `Person` was selected based on the value in the text field (if they typed in the person's whole name but never tapped an autocomplete suggestion).

**Comment by jifalops** [comment]
See the updated [example](https://github.com/jifalops/simple_autocomplete_formfield/blob/master/example/lib/main.dart).
